### ISSUE TITLE
Admin -Pelanggan Content

### ISSUE THREAD

**Issue by Ocph23** [Ocph23/DevyProject#10]
Include CRUD Pemasangan

**Comment by yaqinwahid** [comment]
![pelanggan](https://user-images.githubusercontent.com/32204505/43469708-c21d63bc-9521-11e8-8627-42e3a7f82e1d.png)

I think on pelanggan menu we use nav tab, do you agree ?

**Comment by Ocph23** [comment]
How the Stories this procces ??

**Comment by Ocph23** [comment]
I think ,
Pelanggan Register them self by android apps and then Admin Just Validate,

**Comment by yaqinwahid** [comment]
oh sorry i'm understand now heheh
Alright, so please delete the add new pelanggan menu.
Pelanggan will register themselves by android and fill thei biodata. admin just verifying it
