### ISSUE TITLE
Admin -Pengaduan Content

### ISSUE THREAD

**Issue by Ocph23** [Ocph23/DevyProject#12]
Include Pengaduan CRUD PRoccess

**Comment by yaqinwahid** [comment]
![pengaduan](https://user-images.githubusercontent.com/32204505/43534663-e9b6eae8-95f2-11e8-8c3c-cbd74c9fbca6.png)

Here's the pengaduan menu plan

**Comment by Ocph23** [comment]
I Think ?
Pengaduan Pelangan Push From Android Apps ?

**Comment by yaqinwahid** [comment]
Oh yes i see,
So there is no add new pengaduan from admin.
So please delete the add icon
