### ISSUE TITLE
Request Change Password

### ISSUE THREAD

**Issue by Ocph23** [Ocph23/DevyProject#15]
item/input  just Email.

User input Email & send it.

=> System Will Send Browser Link via email and user can change Password in Browser

**Comment by yaqinwahid** [comment]
So the form same with the forgot password ?

![forgot password form](https://user-images.githubusercontent.com/32204505/43402528-e72b5ada-944d-11e8-9ba2-09c0ed5ed95a.png)

**Comment by yaqinwahid** [comment]
Or can i make the form like this?

![change password](https://user-images.githubusercontent.com/32204505/43402610-166cd0ee-944e-11e8-80ba-e392033cd627.png)
