### ISSUE TITLE
Design Content Pemasangan -Android

### ISSUE THREAD

**Issue by mymp21** [Ocph23/DevyProject#19]
Tolong Design Content Pemasangan

**Comment by yaqinwahid** [comment]
![pemasangan baru](https://user-images.githubusercontent.com/32204505/43687383-1fb9db18-990f-11e8-91af-7874438c20a0.png)

Input pemasangan baru

**Comment by yaqinwahid** [comment]
![pemasangan detail](https://user-images.githubusercontent.com/32204505/43687444-3daaa6ce-9910-11e8-843a-6b7989cbc112.png)

Detail Pemasangan

**Comment by Ocph23** [comment]
Where User Can Call Details Pemasangan ?
