### ISSUE TITLE
Login dan Registrasi Form

### ISSUE THREAD

**Issue by Ocph23** [Ocph23/DevyProject#4]
Please Add Login & Registration Form

**Comment by yaqinwahid** [comment]
![login form](https://user-images.githubusercontent.com/32204505/43270033-10ceb3d6-912f-11e8-835c-b13f4fdcd949.png)

Here's the login form.
For the avatar image u can use the PLN logo or just the avatar. Whatever u think better 👍

**Comment by yaqinwahid** [comment]
![regiter form](https://user-images.githubusercontent.com/32204505/43270967-4aa45f1e-9131-11e8-8401-97e74af9c02d.png)

I wanna to make it simple to register 😆 
What do u think?

**Comment by Ocph23** [comment]
![image](https://user-images.githubusercontent.com/8438698/43325298-44a51c78-91f1-11e8-94d1-8c6df5be1a84.png)

![image](https://user-images.githubusercontent.com/8438698/43325329-58db4c8a-91f1-11e8-8f45-59d77255cd03.png)
