### ISSUE TITLE
Petugas -Petugas Content

### ISSUE THREAD

**Issue by Ocph23** [Ocph23/DevyProject#8]
Include CRUD Proccess

**Comment by yaqinwahid** [comment]
![petugas dashboard](https://user-images.githubusercontent.com/32204505/43368033-65b7abb4-9391-11e8-9580-87a68968d7bb.png)

Pengaduan Menu

**Comment by yaqinwahid** [comment]
![pemasangan](https://user-images.githubusercontent.com/32204505/43368120-22e9ef66-9393-11e8-83c2-88fc8fbeb874.png)

Pemasangan Menu

**Comment by yaqinwahid** [comment]
![pemasangan](https://user-images.githubusercontent.com/32204505/43368360-c2210b98-9396-11e8-9a5c-f9e362f70653.png)

Pemasangan Menu

**Comment by Ocph23** [comment]
Tambahkan Untuk melihat detail Pelanggan

**Comment by yaqinwahid** [comment]
![dashboard](https://user-images.githubusercontent.com/32204505/43404458-8326cd94-9452-11e8-9094-29e78d10ace6.png)

Bang, here the dashboard plan

**Comment by yaqinwahid** [comment]
![pemasangan](https://user-images.githubusercontent.com/32204505/43404643-ef23c22c-9452-11e8-8e70-a6b6268f427f.png)

Bang, i want when petugas click the pelanggan name will show detail in modal.
Wait i will try to design the modal interface

**Comment by yaqinwahid** [comment]
![modal](https://user-images.githubusercontent.com/32204505/43437976-cc2b8af6-94c6-11e8-979c-565ad1605483.png)

Here's the modal for User details

**Comment by yaqinwahid** [comment]
![profile](https://user-images.githubusercontent.com/32204505/43438559-c776719e-94c9-11e8-9650-ebde62cd5a56.png)


Here's the profile design

Note: Nomor identitas dan scan identitas just for pelanggan profile

**Comment by yaqinwahid** [comment]
![profile](https://user-images.githubusercontent.com/32204505/43438810-0eccc38a-94cb-11e8-9f30-29ace732c4d2.png)

No Identitas and File identitas just for pelanggan

**Comment by yaqinwahid** [comment]
Sorry for user's modal. can you add feature download identitas. so petugas can get the file.
Thanks bang

**Comment by Ocph23** [comment]
like this 
![image](https://user-images.githubusercontent.com/8438698/43488231-f68f7540-9553-11e8-94f2-6ab7f38c3ea8.png)

**Comment by yaqinwahid** [comment]
Thats okay bang. thanks
