### ISSUE TITLE
Admin - Pemasangan Content

### ISSUE THREAD

**Issue by Ocph23** [Ocph23/DevyProject#9]
Include CRUD Pemasangan

**Comment by yaqinwahid** [comment]
![pemasangan](https://user-images.githubusercontent.com/32204505/43641965-92e1eafa-9760-11e8-8c89-f8b66ff999bb.png)

Here's the plan. i'm still little confusing about the flow hehe. but let me explain it from my mind,
When customers have done input their pemasangan data from andoid, the admin will 
verifying it then input petugas and biaya for it. 

Do you agree or have another plan?
